# Site settings
title: Richard Meadows
email:
description:
  Homepage of Richard Meadows
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.richard.fish" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

excerpt_separator: <!--more-->
