# Site settings
title: Richard Meadows
email:
description:
  Homepage of Richard Meadows
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.richard.fish" # the base hostname & protocol for your site

# Build settings
markdown: redcarpet

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

excerpt_separator: <!--more-->
